
name: Update Instruction File

on:
  push:

jobs:
  update-instruction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create branch
        run: |
          BRANCHES=$(git branch -a --format="%(refname:short)")
          for BRANCH in $BRANCHES; do
            git checkout $BRANCH
            git switch -c update-instruction-$BRANCH
            echo "Creating branch update-instruction-$BRANCH"
            git push origin update-instruction-$BRANCH
          done

      - name: Update instruction file
        run: |
          BRANCHES=$(git branch -a --format="%(refname:short)")
          for BRANCH in $BRANCHES; do
            git checkout update-instruction-$BRANCH
            echo "Updating instruction file in branch $BRANCH"
            echo "Updated content" > instruction.txt
            git add instruction.txt
            git commit -m "Update instruction file"
            git push origin update-instruction-$BRANCH
          done

      - name: Create pull requests
        run: |
          BRANCHES=$(git branch -a --format="%(refname:short)")
          for BRANCH in $BRANCHES; do
            BASE_BRANCH=${BRANCH#remotes/origin/}
            PULL_BRANCH="update-instruction-$BRANCH"
            echo "Creating pull request from $PULL_BRANCH to $BASE_BRANCH"
            gh pr create --base $BASE_BRANCH --head $PULL_BRANCH --title "Update instruction file" --body "Automated update of instruction file"
          done
