name: PR Description Validator
on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - patch-1
      - develop
      - release-*
    paths:
      - '.github/workflows/**'
jobs:
  validate-pr-description:
    name: Validate PR Title and Description
    runs-on: ubuntu-latest
    steps:
      - name: No check required
        run: echo "No check required for this PR"
