
name: Update Instruction File

on:
  push:
    

jobs:
  update_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config user.email "zeeshan.ijaz@emumba.com"
          git config user.name "ZeeshanIB"

      - name: Update file in branches
        run: |
          FILE_NAME="instruction.txt"
          BRANCHES=$(git branch -a --format="%(refname:short)")
          for BRANCH in $BRANCHES; do
            git checkout $BRANCH
            echo "Updating $FILE_NAME in branch $BRANCH"
            echo "Updated content in main " > $FILE_NAME
            git add $FILE_NAME
            git commit -m "Update $FILE_NAME in $BRANCH"
            git push origin $BRANCH
          done
