name: Title Pattern Check

on:
  pull_request:
    types: [opened, edited]
    branches:
      - main   # Specify the branches where this check should run
      - develop
      - feature/* # Add more branches as needed

jobs:
  check-title-pattern:
    runs-on: ubuntu-latest

    steps:
      - name: Check for required pattern in title
        id: check_title_pattern
        uses: actions/github-script@v6
        with:
          script: |
            const { context, core } = require("@actions/github");

            // Define the required pattern for the PR title
            const pattern = "DOP-";

            // Get the pull request title
            const title = context.payload.pull_request.title || "";

            // Check if the title matches the pattern
            if (!pattern.test(title)) {
              core.setFailed(
                "The PR title does not match the required pattern. Please update the title to follow the format."
              );
            }
