
name: Update Instruction

on:
  push:
    branches:
      - '*'

jobs:
  update-instruction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "your-email@example.com"
          git config user.name "Your Name"

      - name: Update instruction.txt in all branches
        run: |
          FILE_NAME="instruction.txt"
          BRANCHES=$(git branch -a --format="%(refname:short)")

          for BRANCH in $BRANCHES; do
            git checkout $BRANCH
            echo "Updating $FILE_NAME in branch $BRANCH"
            echo "Updated content" > $FILE_NAME
            git add $FILE_NAME
            git commit -m "Update $FILE_NAME in $BRANCH"
            git push origin $BRANCH
          done
