name: Update Instruction File

on:
  push:
    branches:
      - main

jobs:
  update-instruction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Instruction File
        run: |
          FILE_NAME="instruction.txt"
          BRANCHES=$(git branch -a --format="%(refname:short)")
          for BRANCH in $BRANCHES; do
            git checkout $BRANCH
            echo "Updating $FILE_NAME in branch $BRANCH"
            echo "Updated content" > $FILE_NAME
            git add $FILE_NAME
            git commit -m "Update $FILE_NAME in $BRANCH"
            git push origin $BRANCH
          done
