
name: Update Instruction

on:
  push:
    branches:
      - '*'

jobs:
  update-instruction:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update Instruction
        run: |
        
          FILE_NAME="instruction.txt"
          BRANCHES=$(git branch -a | grep remotes | grep -v HEAD | grep -v main) 
          
          for BRANCH in $BRANCHES; do
            git switch ${BRANCH#remotes/origin/}
            echo "Updating $FILE_NAME in branch ${BRANCH#remotes/origin/}"
            echo "Updated content" > $FILE_NAME
            git add $FILE_NAME
            git commit -m "Update $FILE_NAME in ${BRANCH#remotes/origin/}"
            git push origin ${BRANCH#remotes/origin/}
          done
