
name: Update Instruction

on:
  push:
    branches:
      - '*'

jobs:
  update-instruction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "your-email@example.com"
          git config user.name "Your Name"

      - name: Update file in all branches
        run: |
          for branch in $(git branch -r --format="%(refname:short)"); do
            git checkout "$branch"
            echo "Updating instruction.txt in branch $branch"
            echo "Updated content" > instruction.txt
            git add instruction.txt
            git commit -m "Update instruction.txt in $branch"
            git push origin "$branch"
          done
