name: PR Description Validator

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - patch-1
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validate-pr-description:
    name: Validate PR Description
    runs-on: ubuntu-latest
    steps:
      - name: Set up workspace
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate PR Description
        run: |
          # Fetch PR description using jq
          PR_DESCRIPTION=$(jq -r ".pull_request.body" "$GITHUB_EVENT_PATH")

          # Define keywords (add keywords here as needed)
          KEYWORDS=("DOP-" "ZTNA-" "UZ-")

          # Initialize a flag to check if any valid pattern is found
          pattern_found=false

          # Check for each keyword followed by exactly four digits, case-sensitively
          for keyword in "${KEYWORDS[@]}"; do
            if echo "$PR_DESCRIPTION" | grep -qE "${keyword}[0-9]{4}"; then
              pattern_found=true
              break
            fi
          done

          # Fail the job if no valid pattern is found
          if [ "$pattern_found" = false ]; then
            echo "PR description does not contain any of the required patterns (e.g., DOP-1234, ZTNA-5678, UZ-9101)."
            exit 1
          fi
