name: Validate PR Description
on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - patch-1
      - develop
      - release-*
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validate-pr-description:
    name: Validate PR Title and Description
    runs-on: ubuntu-latest
    steps:
      - name: Set up workspace
        uses: actions/checkout@v2

      - name: Fetch Changed Files
        id: files
        run: |
          CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Skip Validation if Only Workflows Changed
        if: ${{ contains(env.CHANGED_FILES, '.github/workflows/') && env.CHANGED_FILES == '.github/workflows/' }}
        run: |
          echo "Only workflow files changed. Skipping validation."
          exit 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate PR Title and Description
        run: |
          # Fetch PR description and title using jq
          PR_DESCRIPTION=$(jq -r ".pull_request.body" "$GITHUB_EVENT_PATH")
          PR_TITLE=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")

          # Debugging: print out PR title and description
          echo "PR Title: $PR_TITLE"
          echo "PR Description: $PR_DESCRIPTION"

          # Define keywords (add keywords here as needed)
          KEYWORDS=("DOP-" "ZTNA-" "UZ-")

          # Initialize a flag to check if any valid pattern is found
          pattern_found=false

          # Check the PR title for valid patterns
          for keyword in "${KEYWORDS[@]}"; do
            if echo "$PR_TITLE" | grep -qE "${keyword}[0-9]{4}"; then
              pattern_found=true
              echo "Valid ticket number found in PR title."
              break
            fi
          done

          # If no valid pattern found in title, check the PR description
          if [ "$pattern_found" = false ] && [[ "$PR_DESCRIPTION" != "null" && -n "$PR_DESCRIPTION" ]]; then
            # Check the entire PR description for valid ticket numbers
            for keyword in "${KEYWORDS[@]}"; do
              if echo "$PR_DESCRIPTION" | grep -qE "${keyword}[0-9]{4}"; then
                pattern_found=true
                echo "Valid ticket number found in PR description."
                break
              fi
            done
          fi

          # Fail the job if no valid pattern is found
          if [ "$pattern_found" = false ]; then
            echo "PR must contain a valid 'Ticket number:' with one of the required patterns in either the title or description (e.g., Ticket number: DOP-1234, Ticket number: ZTNA-5678, Ticket number: UZ-9101)."
            exit 1
          fi
